
import json

# augenerated by chatgpt, not tested yet, may contain errors
def build_entity_extraction_prompt(text):
    return (
        "Extract the entities from the following text and return only valid JSON with an 'entities' list. "
        "Do not include markdown, code fences, or any explanation.\n\n"
        f"Text:\n{text}"
    )


def build_relation_extraction_prompt(text, entities):
    entity_block = json.dumps(entities, ensure_ascii=False, indent=2)
    return (
        "Extract the relations between the given entities and return only valid JSON with a 'triples' list. "
        "Do not include markdown, code fences, or any explanation.\n\n"
        f"Entities:\n{entity_block}\n\n"
        f"Text:\n{text}"
    )
